# Generated by Django 2.2 on 2019-10-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.TextField(max_length=50)),
                ('date', models.DateTimeField()),
                ('link', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=256)),
            ],
            options={
                'ordering': ['name', '-date'],
            },
        ),
    ]
