# Generated by Django 2.2 on 2019-10-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
